export const GET_COMMODITY_LIST_REQUEST = "GET_COMMODITY_LIST_REQUEST";
export const GET_COMMODITY_LIST_SUCCESS = "GET_COMMODITY_LIST_SUCCESS";
export const GET_COMMODITY_LIST_FAIL = "GET_COMMODITY_LIST_FAIL";

export const GET_COMMODITY_LIST_BY_CATEGORY_REQUEST = "GET_COMMODITY_LIST_BY_CATEGORY_REQUEST";
export const GET_COMMODITY_LIST_BY_CATEGORY_SUCCESS = "GET_COMMODITY_LIST_BY_CATEGORY_SUCCESS";
export const GET_COMMODITY_LIST_BY_CATEGORY_FAIL = "GET_COMMODITY_LIST_BY_CATEGORY_FAIL";

export const GET_COMMODITY_REQUEST = "GET_COMMODITY_REQUEST";
export const GET_COMMODITY_SUCCESS = "GET_COMMODITY_SUCCESS";
export const GET_COMMODITY_FAIL = "GET_COMMODITY_FAIL";



export const ADD_COMMODITY_REQUEST = "ADD_COMMODITY_REQUEST";
export const ADD_COMMODITY_SUCCESS = "ADD_COMMODITY_SUCCESS";
export const ADD_COMMODITY_FAIL = "ADD_COMMODITY_FAIL"

export const UPDATE_COMMODITY_REQUEST = "UPDATE_COMMODITY_REQUEST";
export const UPDATE_COMMODITY_SUCCESS = "UPDATE_COMMODITY_SUCCESS";
export const UPDATE_COMMODITY_FAIL = "UPDATE_COMMODITY_FAIL";


export const REMOVE_COMMODITY_REQUEST = "REMOVE_COMMODITY_REQUEST";
export const REMOVE_COMMODITY_SUCCESS = "REMOVE_COMMODITY_SUCCESS";
export const REMOVE_COMMODITY_FAIL = "REMOVE_COMMODITY_FAIL";

export const CLONE_COMMODITY_REQUEST = 'CLONE_COMMODITY_REQUEST';
export const CLONE_COMMODITY_SUCCESS = 'CLONE_COMMODITY_SUCCESS';
export const CLONE_COMMODITY_FAIL = 'CLONE_COMMODITY_FAIL';