export const CHANGE_SHOP_REQUEST = 'CHANGE_SHOP_REQUEST';
//商店设置
export const ADD_SHOP_REQUEST = 'ADD_SHOP_REQUEST';
export const ADD_SHOP_SUCCESS = 'ADD_SHOP_SUCCESS';
export const ADD_SHOP_FAIL = 'ADD_SHOP_FAIL';

export const GET_SHOP_LIST_BY_CREATED_SHOP_AND_LEVEL_REQUEST = 'GET_SHOP_LIST_BY_CREATED_SHOP_AND_LEVEL_REQUEST';
export const GET_SHOP_LIST_BY_CREATED_SHOP_AND_LEVEL_SUCCESS = 'GET_SHOP_LIST_BY_CREATED_SHOP_AND_LEVEL_SUCCESS';
export const GET_SHOP_LIST_BY_CREATED_SHOP_AND_LEVEL_FAIL = 'GET_SHOP_LIST_BY_CREATED_SHOP_AND_LEVEL_FAIL';

export const GET_SHOP_LIST_BY_CLONED_SHOP_AND_LEVEL_REQUEST = 'GET_SHOP_LIST_BY_CLONED_SHOP_AND_LEVEL_REQUEST';
export const GET_SHOP_LIST_BY_CLONED_SHOP_AND_LEVEL_SUCCESS = 'GET_SHOP_LIST_BY_CLONED_SHOP_AND_LEVEL_SUCCESS';
export const GET_SHOP_LIST_BY_CLONED_SHOP_AND_LEVEL_FAIL = 'GET_SHOP_LIST_BY_CLONED_SHOP_AND_LEVEL_FAIL';

export const GET_SHOP_LIST_REQUEST = 'GET_SHOP_LIST_REQUEST';
export const GET_SHOP_LIST_SUCCESS = 'GET_SHOP_LIST_SUCCESS';
export const GET_SHOP_LIST_FAIL = 'GET_SHOP_LIST_FAIL';

export const GET_SHOP_REQUEST = 'GET_SHOP_REQUEST';
export const GET_SHOP_SUCCESS = 'GET_SHOP_SUCCESS';
export const GET_SHOP_FAIL = 'GET_SHOP_FAIL';

export const UPDATE_SHOP_REQUEST = 'UPDATE_SHOP_REQUEST';
export const UPDATE_SHOP_SUCCESS = 'UPDATE_SHOP_SUCCESS';
export const UPDATE_SHOP_FAIL = 'UPDATE_SHOP_FAIL';

export const REMOVE_SHOP_REQUEST = 'REMOVE_SHOP_REQUEST';
export const REMOVE_SHOP_SUCCESS = 'REMOVE_SHOP_SUCCESS';
export const REMOVE_SHOP_FAIL = 'REMOVE_SHOP_FAIL';


//商品类型设置
export const ADD_COMMODITY_CATE_REQUEST = 'ADD_COMMODITY_CATE_REQUEST';
export const ADD_COMMODITY_CATE_SUCCESS = 'ADD_COMMODITY_CATE_SUCCESS';
export const ADD_COMMODITY_CATE_FAIL = 'ADD_COMMODITY_CATE_FAIL';

export const GET_COMMODITY_CATE_LIST_REQUEST = 'GET_COMMODITY_CATE_LIST_REQUEST';
export const GET_COMMODITY_CATE_LIST_SUCCESS = 'GET_COMMODITY_CATE_LIST_SUCCESS';
export const GET_COMMODITY_CATE_LIST_FAIL = 'GET_COMMODITY_CATE_LIST_FAIL';

export const UPDATE_COMMODITY_CATE_REQUEST = 'UPDATE_COMMODITY_CATE_REQUEST';
export const UPDATE_COMMODITY_CATE_SUCCESS = 'UPDATE_COMMODITY_CATE_SUCCESS';
export const UPDATE_COMMODITY_CATE_FAIL = 'UPDATE_COMMODITY_CATE_FAIL';

export const REMOVE_COMMODITY_CATE_REQUEST = 'REMOVE_COMMODITY_CATE_REQUEST';
export const REMOVE_COMMODITY_CATE_SUCCESS = 'REMOVE_COMMODITY_CATE_SUCCESS';
export const REMOVE_COMMODITY_CATE_FAIL = 'REMOVE_COMMODITY_CATE_FAIL';

//配送类型设置
export const ADD_CARRY_CATE_REQUEST = 'ADD_CARRY_CATE_REQUEST';
export const ADD_CARRY_CATE_SUCCESS = 'ADD_CARRY_CATE_SUCCESS';
export const ADD_CARRY_CATE_FAIL = 'ADD_CARRY_CATE_FAIL';

export const GET_CARRY_CATE_LIST_REQUEST = 'GET_CARRY_CATE_LIST_REQUEST';
export const GET_CARRY_CATE_LIST_SUCCESS = 'GET_CARRY_CATE_LIST_SUCCESS';
export const GET_CARRY_CATE_LIST_FAIL = 'GET_CARRY_CATE_LIST_FAIL';

export const UPDATE_CARRY_CATE_REQUEST = 'UPDATE_CARRY_CATE_REQUEST';
export const UPDATE_CARRY_CATE_SUCCESS = 'UPDATE_CARRY_CATE_SUCCESS';
export const UPDATE_CARRY_CATE_FAIL = 'UPDATE_CARRY_CATE_FAIL';

export const REMOVE_CARRY_CATE_REQUEST = 'REMOVE_CARRY_CATE_REQUEST';
export const REMOVE_CARRY_CATE_SUCCESS = 'REMOVE_CARRY_CATE_SUCCESS';
export const REMOVE_CARRY_CATE_FAIL = 'REMOVE_CARRY_CATE_FAIL';

//
export const CHECK_HAVE_COMMODITY_REQUEST = 'CHECK_HAVE_COMMODITY_REQUEST';
export const CHECK_HAVE_COMMODITY_SUCCESS = 'CHECK_HAVE_COMMODITY_SUCCESS';
export const CHECK_HAVE_COMMODITY_FAIL = 'CHECK_HAVE_COMMODITY_FAIL';
